name: regedit
description: A simple clone of the Windows registry editor.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  bitsdojo_window: ^0.1.1+1
  fluent_ui: ^3.6.0
  flutter:
    sdk: flutter
  pluto_grid: ^2.9.1
  provider: ^6.0.2
  win32_registry: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
